### PR TITLE
[feat] GPU support 

### PR DESCRIPTION
**Pull request by JieRen98**

### CODE REVIEW

**Comment by JieRen98** [comment]
Dual is almost done, please check. Please consider applying for a GPU instance for testing cuda codes from GitHub Resources.

**Comment by JieRen98** [comment]
real is supported

**Comment by JieRen98** [comment]
For me, I only need forward. In addition, reverse is not easy to implement because it uses make_shared.

**Comment by JieRen98** [comment]
How to add cuda-toolkit to the test environment? Usually, I use `conda install cuda-toolkit -c nvidia` to install.

**Comment by allanleal** [comment]
Hi @JieRen98 , thanks a lot for your contribution. Are you planning on more additions to this PR?

**Comment by JieRen98** [comment]
For CUDA functions, I think they are mostly done. Of course, we can discuss.

Allan Leal ***@***.***>于2024年1月8日 周一12:53写道：

**Comment by JieRen98** [comment]
CUDA compile options `--expt-relaxed-constexpr --extended-lambda` are necessary, I think we should also add them to the bazel configuration file.

**Comment by JieRen98** [comment]
Workflows may need to change too.

**Pull request merged**
