### PR TITLE
[autodiff/forward] Simplify higher order derivatives

### PR DESCRIPTION
**Pull request by supersega**
Add new wrt function overloading. As we discussed #57 users want to use simpler way of higher-order derivatives calculation. I remember that @allanleal thought about changing dual implementation, but I'm not sure that it is necessary and easy to implement. Also, we will get regressions using such an approach. 
```cpp
using dual4th = Dual<double, 4>;

dual4th x = 1.0;
dual4th y = derivative(sin, wrt(x), at(x));

cout << y[0] << endl; // value of the 0th order derivative of sin(x), which is its actual value
cout << y[1] << endl; // value of the 1st order derivative of sin(x)
cout << y[2] << endl; // value of the 2nd order derivative of sin(x)
cout << y[3] << endl; // value of the 3rd order derivative of sin(x)
cout << y[4] << endl; // value of the 4th order derivative of sin(x)
```

Here we calculate 4 derivatives and it's mean that we call sin 4 times, what if the user wants only one in some cases? 

Consolations: We can change the implementation of Dual to avoid recursion, but we should not add overhead to the user, and that's mean that we need wrt in that form which we have =) correct me if I'm wrong.

P.S. FYI @ibell

### CODE REVIEW

**Comment by ibell** [comment]
What happens if you try to get an index out of range?

**Comment by allanleal** [comment]
Hi @supersega . 

> Here we calculate 4 derivatives and it's mean that we call sin 4 times, what if the user wants only one in some cases?

We know that `d sin(x)/dx` is `cos(x)` and `d cos(x)/dx` is `-sin(x)`. These recurrences would be used in the implementation of higher order derivatives (10th order derivative of `sin(x)` would actually only require one evaluation of `std::sin` and one of `std::cos`, not 10). For `exp(x)`, for example, we would only require one evaluation of function `std::exp`; the same for `log(x)` and a few other mathematical functions. So, there would be no overhead here. In fact, the current recursive implementation causes memory overhead (`Nth` order requires `2**N` doubles; compare this with the `N+1` memory requirement of the new implementation I have in mind!) :)


Hi @ibell 

> What happens if you try to get an index out of range?

You would see a compile error because of the use of `std::array` to store the value and derivatives! If you actually mean using `wrt<4>(x)` in this PR proposal of @supersega , in which only up to 2 should be used, you'll most likely also get a compile error.

**Comment by allanleal** [comment]
> Here we calculate 4 derivatives and it's mean that we call sin 4 times, what if the user wants only one in some cases?

Further clarifications. An Nth order derivative computation using automatic differentiation would also compute the other lower order derivatives. There is no overhead here either, because this is how you would compute them anyway manually. 

Check below how we would compute the derivatives of `exp(x)` up to *n*-th order. 

Things to note first: `x[0]` is the value of `x`, `x[i]` for `1 < i <= n`are seed values to control partial derivative computation.

image

Note above that to compute `exp(x)[i]` we evaluate first `exp(x)[i-1]`. Also note that `exp(x)[0]` is `std::exp(x[0])` and computed only once!

**Comment by supersega** [comment]
Hi @allanleal thanks for explanation. Looks like I have some gaps in theory =) 
If I understand correctly, we should remake all expression nodes with compile time for loop?

**Comment by allanleal** [comment]
> If I understand correctly, we should remake all expression nodes with compile time for loop?

What I mean is that those `n+1` statements in the figure above (for evaluating `exp` on a future/new `dual` type) would be expanded at compile-time, instead of a regular, runtime for loop.

**Comment by supersega** [comment]
Yes, I see. Btw, how to deal with mul expression in this case?

**Comment by allanleal** [comment]
image

Above, multiplication of `x` and `y`.

I have already done this analytical expansion for most mathematical operations; just need to implement them! :)

**Comment by supersega** [comment]
Ah, now I see. If you had time, I would be glad to discuss it in evening(after office hours) in gitter.

**Comment by allanleal** [comment]
Sure! There could indeed have a regression with this new implementation, but this would come with great benefits to future (and also current) users.

**Comment by supersega** [comment]
@alanleal, sounds like we can merge this PR, since you leave class Dual ;)

**Comment by allanleal** [comment]
@supersega Sounds good. Could you please just add this usage in one of the tutorial examples on computing higher-order diff? ;)

Otherwise even us can forget about this usage capability in the future!

**Comment by supersega** [comment]
But I’ve already updated examples)

**Comment by allanleal** [comment]
OK, of course. :)

**Comment by allanleal** [comment]
Great, done! Thanks!

**Pull request merged**
